In [2]:
import pandas as pd 
from collections import Counter

In [3]:
df_cand=pd.read_json(r"D:\__Projects\AI-matching-module\Data_json\candidates\candidates (2).json")
df_job=pd.read_json(r"D:\__Projects\AI-matching-module\Data_json\jobs\jobs (1).json")

In [4]:
df_cand.head()

,id,fullName,headline,location,yearsOfExperience,skills,availability,updatedAt,status,score,summary,languages,education,links,experience,projects,notes
0,c-001,Lina Hassan,"Frontend Engineer | React, TypeScript | Design...","Cairo, Egypt",4,"[React, TypeScript, CSS, Storybook, Accessibil...",2 weeks,2026-02-03,Open to work,86,Builds scalable UI component libraries and imp...,"[Arabic, English]",BSc Computer Engineering,"{'portfolio': 'https://example.com/lina', 'git...","[{'company': 'NileSoft', 'title': 'Frontend En...","[{'name': 'Component Library', 'description': ...","[{'date': '2026-01-25', 'text': 'Strong UI cra..."
1,c-002,Omar El-Sayed,"Frontend Engineer | React Query, Redux Toolkit...","Alexandria, Egypt",5,"[React, Redux Toolkit, React Query, Vite, Vite...",Immediate,2026-02-05,Open to work,90,"Focuses on app performance, caching strategies...","[Arabic, English]",BSc Computer Science,"{'portfolio': 'https://example.com/omar', 'git...","[{'company': 'DeltaApps', 'title': 'Frontend E...","[{'name': 'Analytics Dashboard', 'description'...","[{'date': '2026-02-01', 'text': 'Very strong o..."
2,c-003,Sara Nabil,"Frontend Developer | Next.js, React | UX-first","Giza, Egypt",3,"[React, Next.js, Tailwind, Figma, Accessibilit...",1 month,2026-01-29,Interviewing,82,UX-first developer with strong layout instinct...,"[Arabic, English]",BSc Information Systems,"{'portfolio': 'https://example.com/sara', 'git...","[{'company': 'Cedar Studio', 'title': 'Fronten...","[{'name': 'Recruitment Portal UI', 'descriptio...","[{'date': '2026-01-30', 'text': 'Great eye for..."
3,c-004,Youssef Abdelrahman,Frontend Engineer | Vue → React | UI Architecture,"Cairo, Egypt",6,"[React, Vue, TypeScript, CSS Modules, Testing ...",2 weeks,2026-02-02,Open to work,88,"Experienced in large codebases, migrations, an...","[Arabic, English]",BSc Software Engineering,"{'portfolio': 'https://example.com/youssef', '...","[{'company': 'NorthBridge', 'title': 'Senior F...","[{'name': 'Design System Migration', 'descript...","[{'date': '2026-02-02', 'text': 'Strong archit..."
4,c-005,Mariam Fathy,"Frontend Engineer | React, D3 | Data Visualiza...","Mansoura, Egypt",4,"[React, TypeScript, D3, Recharts, CSS, React H...",Immediate,2026-01-27,Open to work,84,Builds dashboards and data-heavy UIs with a fo...,"[Arabic, English]",BSc Computer Engineering,"{'portfolio': 'https://example.com/mariam', 'g...","[{'company': 'VizCraft', 'title': 'Frontend En...","[{'name': 'Hiring Analytics', 'description': '...","[{'date': '2026-01-28', 'text': 'Good for data..."

In [5]:
df_job

,id,title,description,requirements
0,j-001,Frontend Engineer (React) — UI Craft,We’re building a design-forward recruitment pl...,"{'mustHaveSkills': ['React', 'TypeScript', 'CS..."
1,j-002,Senior Frontend Engineer — Performance & Data,We need a senior frontend engineer for a candi...,"{'mustHaveSkills': ['React', 'TypeScript', 'Pe..."
2,j-003,Frontend Engineer — Design Systems,You will help scale a design system used acros...,"{'mustHaveSkills': ['React', 'TypeScript', 'St..."
3,j-004,Frontend Engineer — Data Visualization,"We’re building recruiter analytics: funnels, b...","{'mustHaveSkills': ['React', 'TypeScript', 'Da..."
4,j-005,Frontend Engineer — Forms & Validation UX,You will build recruiter workflows that includ...,"{'mustHaveSkills': ['React', 'TypeScript', 'Fo..."

In [6]:
import json
with open(r"D:\__Projects\AI-matching-module\Data_json\jobs\jobs (1).json", "r", encoding="utf-8") as f:
    df_job = json.load(f)
all_required_skills_job = set()
for job in df_job:
    all_required_skills_job.update(job['requirements']['mustHaveSkills'])
    all_required_skills_job.update(job['requirements']['niceToHaveSkills'])

In [8]:
all_required_skills_job

{'Accessibility',
 'CSS',
 'CSS Modules',
 'Code Splitting',
 'D3',
 'Data Visualization',
 'Design Tokens',
 'Error Handling',
 'Forms',
 'Lighthouse',
 'Monorepos',
 'Performance',
 'React',
 'React Hook Form',
 'React Query',
 'React Router',
 'Recharts',
 'Storybook',
 'TanStack Table',
 'Testing Library',
 'TypeScript',
 'URL State',
 'Visual Regression Testing',
 'Vitest',
 'Zod'}

In [13]:
import json
with open(r"D:\__Projects\AI-matching-module\Data_json\candidates\candidates (2).json", "r", encoding="utf-8") as f:
    df_job = json.load(f)

all_required_skills_cand = set()
for job in df_job:
    all_required_skills_cand.update(job["skills"])

In [16]:
all_required_skills_cand

{'ARIA',
 'Accessibility',
 'Angular',
 'Animations',
 'Apollo',
 'Axios',
 'CSS',
 'CSS Modules',
 'Code Splitting',
 'Cypress',
 'D3',
 'Design Tokens',
 'Error Handling',
 'Express',
 'Figma',
 'Forms',
 'Framer Motion',
 'Git',
 'GraphQL',
 'Jasmine',
 'JavaScript',
 'Jest',
 'Keyboard UX',
 'Lighthouse',
 'MSW',
 'Maps',
 'Monorepos',
 'Next.js',
 'Node.js',
 'Performance',
 'React',
 'React Hook Form',
 'React Native',
 'React Query',
 'React Router',
 'Recharts',
 'Redux Toolkit',
 'Responsive Design',
 'RxJS',
 'SCSS',
 'Sass',
 'Secure UI',
 'State Machines',
 'Storybook',
 'Styled Components',
 'Tailwind',
 'TanStack Table',
 'Testing',
 'Testing Library',
 'TypeScript',
 'UI Components',
 'URL State',
 'Vite',
 'Vitest',
 'Vue',
 'Webpack',
 'Zod',
 'i18n'}

In [9]:
cout=Counter()
for i in df["skills"]:
    for j in i:
        cout[j]+=1
print(cout.most_common(50))
len(cout)

[('React', 30), ('TypeScript', 23), ('CSS', 22), ('Accessibility', 9), ('React Router', 7), ('Vite', 6), ('Vitest', 6), ('Figma', 6), ('Testing Library', 6), ('React Query', 5), ('JavaScript', 5), ('Storybook', 4), ('Tailwind', 2), ('React Hook Form', 2), ('ARIA', 2), ('Responsive Design', 2), ('Framer Motion', 2), ('Jest', 1), ('Redux Toolkit', 1), ('Sass', 1), ('Next.js', 1), ('Cypress', 1), ('Vue', 1), ('CSS Modules', 1), ('Webpack', 1), ('D3', 1), ('Recharts', 1), ('Angular', 1), ('RxJS', 1), ('SCSS', 1), ('Jasmine', 1), ('React Native', 1), ('Styled Components', 1), ('Lighthouse', 1), ('Code Splitting', 1), ('Node.js', 1), ('Express', 1), ('Zod', 1), ('Git', 1), ('Animations', 1), ('Keyboard UX', 1), ('GraphQL', 1), ('Apollo', 1), ('MSW', 1), ('i18n', 1), ('Maps', 1), ('TanStack Table', 1), ('Design Tokens', 1), ('Monorepos', 1), ('Performance', 1)]

58